-- Meeting ownership lookups power the organizer dashboard.
CREATE INDEX "meetings_organizer_id_idx" ON "meetings"("organizer_id");

-- Existing development participants receive one-time random values before the
-- columns become required. New values are generated by the application.
ALTER TABLE "participants"
ADD COLUMN "display_name_normalized" TEXT,
ADD COLUMN "session_token_hash" TEXT;

UPDATE "participants"
SET
  "display_name_normalized" = lower(trim("display_name")),
  "session_token_hash" = md5(random()::text || clock_timestamp()::text || "id");

ALTER TABLE "participants"
ALTER COLUMN "display_name_normalized" SET NOT NULL,
ALTER COLUMN "session_token_hash" SET NOT NULL;

DROP INDEX "uniq_meeting_display_name";

CREATE UNIQUE INDEX "participants_session_token_hash_key"
ON "participants"("session_token_hash");

CREATE UNIQUE INDEX "uniq_meeting_display_name_normalized"
ON "participants"("meeting_id", "display_name_normalized");

CREATE INDEX "participants_meeting_id_idx" ON "participants"("meeting_id");

CREATE UNIQUE INDEX "uniq_participant_availability_slot"
ON "availabilities"("participant_id", "datetime_start", "datetime_end");

CREATE INDEX "availabilities_participant_id_idx"
ON "availabilities"("participant_id");
