from pathlib import Path

path = Path(__file__).resolve().parents[1] / "scripts/validate-unified-heatmap.cjs"
text = path.read_text(encoding="utf-8")

start = text.find("async function touchSwipe(")
end = text.find("\n\n(async () => {", start)
if start < 0 or end < 0:
    raise RuntimeError("touchSwipe helper block not found")
text = text[:start] + text[end + 2 :]

old = '''  const swipeArea = mobile.locator('[data-day-swipe="true"] > div').first();\n  const swipeBox = await swipeArea.boundingBox();\n  if (!swipeBox) throw new Error('Swipe area bounds missing');\n  const selectedBeforeSwipe = await mobile.locator('button[data-selected="true"]').count();\n  await touchSwipe(mobileContext, mobile, swipeBox);\n  await mobile.waitForTimeout(250);\n  if ((await mobile.locator('[data-mobile-day-index]').getAttribute('data-mobile-day-index')) !== '1') throw new Error('Dedicated swipe did not move to next day');\n  if (await mobile.locator('button[data-selected="true"]').count() !== selectedBeforeSwipe) throw new Error('Day swipe changed availability');\n'''
new = '''  const selectedBeforeSwipe = await mobile\n    .locator('button[data-selected="true"]')\n    .evaluateAll((elements) =>\n      elements\n        .map((element) => element.getAttribute('data-slot-start'))\n        .filter(Boolean)\n        .sort(),\n    );\n  const swipeTrack = mobile.locator('[data-day-swipe-track="true"]');\n  const swipeContract = await swipeTrack.evaluate((element) => {\n    const style = getComputedStyle(element);\n    return {\n      clientWidth: element.clientWidth,\n      scrollWidth: element.scrollWidth,\n      overflowX: style.overflowX,\n      scrollSnapType: style.scrollSnapType,\n      touchAction: style.touchAction,\n    };\n  });\n  if (swipeContract.scrollWidth <= swipeContract.clientWidth) {\n    throw new Error(`Day navigator is not horizontally scrollable: ${JSON.stringify(swipeContract)}`);\n  }\n  if (!['auto', 'scroll'].includes(swipeContract.overflowX)) {\n    throw new Error(`Day navigator overflow-x is not swipeable: ${swipeContract.overflowX}`);\n  }\n  if (!swipeContract.scrollSnapType.includes('x')) {\n    throw new Error(`Day navigator is missing x scroll snapping: ${swipeContract.scrollSnapType}`);\n  }\n  if (!swipeContract.touchAction.includes('pan-x')) {\n    throw new Error(`Day navigator does not reserve horizontal touch panning: ${swipeContract.touchAction}`);\n  }\n  await swipeTrack.evaluate((element) => {\n    element.scrollTo({ left: element.clientWidth, behavior: 'auto' });\n    element.dispatchEvent(new Event('scroll'));\n  });\n  await mobile.waitForFunction(\n    () => document.querySelector('[data-mobile-day-index]')?.getAttribute('data-mobile-day-index') === '1',\n    undefined,\n    { timeout: 5000 },\n  );\n  await mobile.getByRole('button', { name: 'Previous day' }).click();\n  await mobile.waitForFunction(\n    () => document.querySelector('[data-mobile-day-index]')?.getAttribute('data-mobile-day-index') === '0',\n    undefined,\n    { timeout: 5000 },\n  );\n  const selectedAfterSwipe = await mobile\n    .locator('button[data-selected="true"]')\n    .evaluateAll((elements) =>\n      elements\n        .map((element) => element.getAttribute('data-slot-start'))\n        .filter(Boolean)\n        .sort(),\n    );\n  if (JSON.stringify(selectedAfterSwipe) !== JSON.stringify(selectedBeforeSwipe)) {\n    throw new Error('Dedicated day navigation changed tile selection');\n  }\n  await mobile.getByRole('button', { name: 'Next day' }).click();\n  await mobile.waitForFunction(\n    () => document.querySelector('[data-mobile-day-index]')?.getAttribute('data-mobile-day-index') === '1',\n    undefined,\n    { timeout: 5000 },\n  );\n'''
if old not in text:
    raise RuntimeError("mobile swipe validation block not found")
text = text.replace(old, new, 1)
path.write_text(text, encoding="utf-8")
print("mobile day navigation validation now checks native scroll-snap contract and selection isolation")
